# Target AWS Region
aws_region: us-east-1

# Source bucket name
# source_bucket: vectopus-webp-test
source_bucket: image-engine-private-prod

# Target bucket name
target_bucket: vectopus-webp-test-out
# target_bucket: image-engine-public-prod

# Prefixes to include
include_prefixes:
  - iconify

# Prefixes to exclude
# omit_prefixes:
#   - dog-avatars

# Dry run?
dry_run: true

# Local?
is_local: true

# Upload results to s3?
upload_to_s3: true

local_source: /Users/scott/github/vectopus-code/image-processor/test/input
local_target: /Users/scott/github/vectopus-code/image-processor/test/output

# Archive structure
archive_structure: contributor,family,set,icons

# Garbage collection
auto_cleanup: false

# ffMpeg path
ffmpegPath: /opt/homebrew/bin/ffmpeg

# Webp sizes
webp_sizes:
  thumbnail: 128
  preview: 512
  watermark: 512

# Watermark
watermark_path: /Users/scott/github/vectopus-code/image-processor/assets/watermark.svg

# AWS Role arn
role_arn: arn:aws:iam::511873596089:role/svg-webp-app-role

# Logging output
# 0 = no output
# 1 = output to console
# 2 = output to file
# 3 = output to both
logging_output: 3

# Log file path
logfile: ./output.log

# Work dir
work_dir: "/Volumes/image-processor-ramdisk//Volumes/image-processor-ramdisk/"

# Output dir
output_dir: ./test/output

# Worker Count
worker_pool_size: 10
download_worker_pool_size: 5
process_worker_pool_size: 10

# Use Hardware Acceleration
use_hardware_acceleration: true