package database

import (
	"strings"
	"testing"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// sqlCapture records the SQL statements and bind variables generated by a
// dry-run gorm session. The query functions under test are thin wrappers
// whose contract is the query they build (table, filters, ordering,
// pagination), so the tests assert on the generated SQL rather than on rows,
// which would require a live database.
type sqlCapture struct {
	SQL  []string
	Vars [][]interface{}
}

// last returns the most recently captured statement, failing the test if
// nothing was captured.
func (c *sqlCapture) last(t *testing.T) string {
	t.Helper()
	if len(c.SQL) == 0 {
		t.Fatal("no SQL captured - the query function never built a query")
	}
	return c.SQL[len(c.SQL)-1]
}

// lastVars returns the bind variables of the most recently captured
// statement.
func (c *sqlCapture) lastVars(t *testing.T) []interface{} {
	t.Helper()
	if len(c.Vars) == 0 {
		t.Fatal("no variables captured")
	}
	return c.Vars[len(c.Vars)-1]
}

// containsVar reports whether the captured bind variables include the given
// value.
func containsVar(vars []interface{}, want interface{}) bool {
	for _, v := range vars {
		if v == want {
			return true
		}
	}
	return false
}

// newCaptureService builds a DatabaseService backed by a dry-run gorm
// session that never connects to a database, with an After-query callback
// that records every generated statement.
func newCaptureService(t *testing.T) (*DatabaseService, *sqlCapture) {
	t.Helper()
	db, err := gorm.Open(postgres.Open("host=localhost user=none dbname=none"), &gorm.Config{
		DisableAutomaticPing: true,
		DryRun:               true,
	})
	if err != nil {
		t.Fatalf("failed to open dry-run gorm DB: %v", err)
	}

	capture := &sqlCapture{}
	err = db.Callback().Query().After("gorm:query").Register("test:capture", func(tx *gorm.DB) {
		capture.SQL = append(capture.SQL, tx.Statement.SQL.String())
		capture.Vars = append(capture.Vars, tx.Statement.Vars)
	})
	if err != nil {
		t.Fatalf("failed to register capture callback: %v", err)
	}

	return &DatabaseService{DB: db}, capture
}

// mustContain asserts that the SQL contains every listed fragment.
func mustContain(t *testing.T, sql string, fragments ...string) {
	t.Helper()
	for _, fragment := range fragments {
		if !strings.Contains(sql, fragment) {
			t.Errorf("generated SQL %q does not contain %q", sql, fragment)
		}
	}
}
