// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockImageFile is an autogenerated mock type for the IImageFile type
type MockImageFile struct {
	mock.Mock
}

type MockImageFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageFile) EXPECT() *MockImageFile_Expecter {
	return &MockImageFile_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with no fields
func (_m *MockImageFile) Exists() (bool, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageFile_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockImageFile_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
func (_e *MockImageFile_Expecter) Exists() *MockImageFile_Exists_Call {
	return &MockImageFile_Exists_Call{Call: _e.mock.On("Exists")}
}

func (_c *MockImageFile_Exists_Call) Run(run func()) *MockImageFile_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageFile_Exists_Call) Return(_a0 bool, _a1 error) *MockImageFile_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageFile_Exists_Call) RunAndReturn(run func() (bool, error)) *MockImageFile_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ToJSON provides a mock function with no fields
func (_m *MockImageFile) ToJSON() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToJSON")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockImageFile_ToJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToJSON'
type MockImageFile_ToJSON_Call struct {
	*mock.Call
}

// ToJSON is a helper method to define mock.On call
func (_e *MockImageFile_Expecter) ToJSON() *MockImageFile_ToJSON_Call {
	return &MockImageFile_ToJSON_Call{Call: _e.mock.On("ToJSON")}
}

func (_c *MockImageFile_ToJSON_Call) Run(run func()) *MockImageFile_ToJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageFile_ToJSON_Call) Return(_a0 map[string]interface{}) *MockImageFile_ToJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageFile_ToJSON_Call) RunAndReturn(run func() map[string]interface{}) *MockImageFile_ToJSON_Call {
	_c.Call.Return(run)
	return _c
}

// ToSnakeCase provides a mock function with no fields
func (_m *MockImageFile) ToSnakeCase() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSnakeCase")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockImageFile_ToSnakeCase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSnakeCase'
type MockImageFile_ToSnakeCase_Call struct {
	*mock.Call
}

// ToSnakeCase is a helper method to define mock.On call
func (_e *MockImageFile_Expecter) ToSnakeCase() *MockImageFile_ToSnakeCase_Call {
	return &MockImageFile_ToSnakeCase_Call{Call: _e.mock.On("ToSnakeCase")}
}

func (_c *MockImageFile_ToSnakeCase_Call) Run(run func()) *MockImageFile_ToSnakeCase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageFile_ToSnakeCase_Call) Return(_a0 map[string]interface{}) *MockImageFile_ToSnakeCase_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageFile_ToSnakeCase_Call) RunAndReturn(run func() map[string]interface{}) *MockImageFile_ToSnakeCase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageFile creates a new instance of MockImageFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageFile {
	mock := &MockImageFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
