// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	database "github.com/iconifyit/go-batch-svg-to-webp/src/database"
	mock "github.com/stretchr/testify/mock"

	models "github.com/iconifyit/go-batch-svg-to-webp/src/models"
)

// MockDatabaseService is an autogenerated mock type for the IDatabaseService type
type MockDatabaseService struct {
	mock.Mock
}

type MockDatabaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseService) EXPECT() *MockDatabaseService_Expecter {
	return &MockDatabaseService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDatabaseService) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabaseService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatabaseService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatabaseService_Expecter) Close() *MockDatabaseService_Close_Call {
	return &MockDatabaseService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatabaseService_Close_Call) Run(run func()) *MockDatabaseService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseService_Close_Call) Return(_a0 error) *MockDatabaseService_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabaseService_Close_Call) RunAndReturn(run func() error) *MockDatabaseService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamilies provides a mock function with given fields: params
func (_m *MockDatabaseService) GetFamilies(params database.QueryParams) ([]models.Family, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilies")
	}

	var r0 []models.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) ([]models.Family, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) []models.Family); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Family)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetFamilies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamilies'
type MockDatabaseService_GetFamilies_Call struct {
	*mock.Call
}

// GetFamilies is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetFamilies(params interface{}) *MockDatabaseService_GetFamilies_Call {
	return &MockDatabaseService_GetFamilies_Call{Call: _e.mock.On("GetFamilies", params)}
}

func (_c *MockDatabaseService_GetFamilies_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetFamilies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetFamilies_Call) Return(_a0 []models.Family, _a1 error) *MockDatabaseService_GetFamilies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetFamilies_Call) RunAndReturn(run func(database.QueryParams) ([]models.Family, error)) *MockDatabaseService_GetFamilies_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamily provides a mock function with given fields: params
func (_m *MockDatabaseService) GetFamily(params *database.QueryParams) (*models.Family, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetFamily")
	}

	var r0 *models.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(*database.QueryParams) (*models.Family, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*database.QueryParams) *models.Family); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Family)
		}
	}

	if rf, ok := ret.Get(1).(func(*database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamily'
type MockDatabaseService_GetFamily_Call struct {
	*mock.Call
}

// GetFamily is a helper method to define mock.On call
//   - params *database.QueryParams
func (_e *MockDatabaseService_Expecter) GetFamily(params interface{}) *MockDatabaseService_GetFamily_Call {
	return &MockDatabaseService_GetFamily_Call{Call: _e.mock.On("GetFamily", params)}
}

func (_c *MockDatabaseService_GetFamily_Call) Run(run func(params *database.QueryParams)) *MockDatabaseService_GetFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetFamily_Call) Return(_a0 *models.Family, _a1 error) *MockDatabaseService_GetFamily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetFamily_Call) RunAndReturn(run func(*database.QueryParams) (*models.Family, error)) *MockDatabaseService_GetFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamilyById provides a mock function with given fields: id
func (_m *MockDatabaseService) GetFamilyById(id int) (*models.Family, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilyById")
	}

	var r0 *models.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Family, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Family); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Family)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetFamilyById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamilyById'
type MockDatabaseService_GetFamilyById_Call struct {
	*mock.Call
}

// GetFamilyById is a helper method to define mock.On call
//   - id int
func (_e *MockDatabaseService_Expecter) GetFamilyById(id interface{}) *MockDatabaseService_GetFamilyById_Call {
	return &MockDatabaseService_GetFamilyById_Call{Call: _e.mock.On("GetFamilyById", id)}
}

func (_c *MockDatabaseService_GetFamilyById_Call) Run(run func(id int)) *MockDatabaseService_GetFamilyById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseService_GetFamilyById_Call) Return(_a0 *models.Family, _a1 error) *MockDatabaseService_GetFamilyById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetFamilyById_Call) RunAndReturn(run func(int) (*models.Family, error)) *MockDatabaseService_GetFamilyById_Call {
	_c.Call.Return(run)
	return _c
}

// GetIcon provides a mock function with given fields: params
func (_m *MockDatabaseService) GetIcon(params database.QueryParams) (*models.Icon, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetIcon")
	}

	var r0 *models.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) (*models.Icon, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) *models.Icon); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Icon)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIcon_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIcon'
type MockDatabaseService_GetIcon_Call struct {
	*mock.Call
}

// GetIcon is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetIcon(params interface{}) *MockDatabaseService_GetIcon_Call {
	return &MockDatabaseService_GetIcon_Call{Call: _e.mock.On("GetIcon", params)}
}

func (_c *MockDatabaseService_GetIcon_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetIcon_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetIcon_Call) Return(_a0 *models.Icon, _a1 error) *MockDatabaseService_GetIcon_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIcon_Call) RunAndReturn(run func(database.QueryParams) (*models.Icon, error)) *MockDatabaseService_GetIcon_Call {
	_c.Call.Return(run)
	return _c
}

// GetIconById provides a mock function with given fields: id
func (_m *MockDatabaseService) GetIconById(id int) (*models.Icon, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetIconById")
	}

	var r0 *models.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Icon, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Icon); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Icon)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIconById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIconById'
type MockDatabaseService_GetIconById_Call struct {
	*mock.Call
}

// GetIconById is a helper method to define mock.On call
//   - id int
func (_e *MockDatabaseService_Expecter) GetIconById(id interface{}) *MockDatabaseService_GetIconById_Call {
	return &MockDatabaseService_GetIconById_Call{Call: _e.mock.On("GetIconById", id)}
}

func (_c *MockDatabaseService_GetIconById_Call) Run(run func(id int)) *MockDatabaseService_GetIconById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseService_GetIconById_Call) Return(_a0 *models.Icon, _a1 error) *MockDatabaseService_GetIconById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIconById_Call) RunAndReturn(run func(int) (*models.Icon, error)) *MockDatabaseService_GetIconById_Call {
	_c.Call.Return(run)
	return _c
}

// GetIcons provides a mock function with given fields: params
func (_m *MockDatabaseService) GetIcons(params database.QueryParams) ([]models.Icon, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetIcons")
	}

	var r0 []models.Icon
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) ([]models.Icon, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) []models.Icon); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Icon)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIcons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIcons'
type MockDatabaseService_GetIcons_Call struct {
	*mock.Call
}

// GetIcons is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetIcons(params interface{}) *MockDatabaseService_GetIcons_Call {
	return &MockDatabaseService_GetIcons_Call{Call: _e.mock.On("GetIcons", params)}
}

func (_c *MockDatabaseService_GetIcons_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetIcons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetIcons_Call) Return(_a0 []models.Icon, _a1 error) *MockDatabaseService_GetIcons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIcons_Call) RunAndReturn(run func(database.QueryParams) ([]models.Icon, error)) *MockDatabaseService_GetIcons_Call {
	_c.Call.Return(run)
	return _c
}

// GetIllustration provides a mock function with given fields: params
func (_m *MockDatabaseService) GetIllustration(params database.QueryParams) (*models.Illustration, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetIllustration")
	}

	var r0 *models.Illustration
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) (*models.Illustration, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) *models.Illustration); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Illustration)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIllustration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIllustration'
type MockDatabaseService_GetIllustration_Call struct {
	*mock.Call
}

// GetIllustration is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetIllustration(params interface{}) *MockDatabaseService_GetIllustration_Call {
	return &MockDatabaseService_GetIllustration_Call{Call: _e.mock.On("GetIllustration", params)}
}

func (_c *MockDatabaseService_GetIllustration_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetIllustration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetIllustration_Call) Return(_a0 *models.Illustration, _a1 error) *MockDatabaseService_GetIllustration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIllustration_Call) RunAndReturn(run func(database.QueryParams) (*models.Illustration, error)) *MockDatabaseService_GetIllustration_Call {
	_c.Call.Return(run)
	return _c
}

// GetIllustrationById provides a mock function with given fields: id
func (_m *MockDatabaseService) GetIllustrationById(id int) (*models.Illustration, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetIllustrationById")
	}

	var r0 *models.Illustration
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Illustration, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Illustration); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Illustration)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIllustrationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIllustrationById'
type MockDatabaseService_GetIllustrationById_Call struct {
	*mock.Call
}

// GetIllustrationById is a helper method to define mock.On call
//   - id int
func (_e *MockDatabaseService_Expecter) GetIllustrationById(id interface{}) *MockDatabaseService_GetIllustrationById_Call {
	return &MockDatabaseService_GetIllustrationById_Call{Call: _e.mock.On("GetIllustrationById", id)}
}

func (_c *MockDatabaseService_GetIllustrationById_Call) Run(run func(id int)) *MockDatabaseService_GetIllustrationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseService_GetIllustrationById_Call) Return(_a0 *models.Illustration, _a1 error) *MockDatabaseService_GetIllustrationById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIllustrationById_Call) RunAndReturn(run func(int) (*models.Illustration, error)) *MockDatabaseService_GetIllustrationById_Call {
	_c.Call.Return(run)
	return _c
}

// GetIllustrations provides a mock function with given fields: params
func (_m *MockDatabaseService) GetIllustrations(params database.QueryParams) ([]models.Illustration, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetIllustrations")
	}

	var r0 []models.Illustration
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) ([]models.Illustration, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) []models.Illustration); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Illustration)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetIllustrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIllustrations'
type MockDatabaseService_GetIllustrations_Call struct {
	*mock.Call
}

// GetIllustrations is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetIllustrations(params interface{}) *MockDatabaseService_GetIllustrations_Call {
	return &MockDatabaseService_GetIllustrations_Call{Call: _e.mock.On("GetIllustrations", params)}
}

func (_c *MockDatabaseService_GetIllustrations_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetIllustrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetIllustrations_Call) Return(_a0 []models.Illustration, _a1 error) *MockDatabaseService_GetIllustrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetIllustrations_Call) RunAndReturn(run func(database.QueryParams) ([]models.Illustration, error)) *MockDatabaseService_GetIllustrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetSet provides a mock function with given fields: params
func (_m *MockDatabaseService) GetSet(params *database.QueryParams) (*models.Set, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetSet")
	}

	var r0 *models.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(*database.QueryParams) (*models.Set, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*database.QueryParams) *models.Set); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(*database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSet'
type MockDatabaseService_GetSet_Call struct {
	*mock.Call
}

// GetSet is a helper method to define mock.On call
//   - params *database.QueryParams
func (_e *MockDatabaseService_Expecter) GetSet(params interface{}) *MockDatabaseService_GetSet_Call {
	return &MockDatabaseService_GetSet_Call{Call: _e.mock.On("GetSet", params)}
}

func (_c *MockDatabaseService_GetSet_Call) Run(run func(params *database.QueryParams)) *MockDatabaseService_GetSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetSet_Call) Return(_a0 *models.Set, _a1 error) *MockDatabaseService_GetSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetSet_Call) RunAndReturn(run func(*database.QueryParams) (*models.Set, error)) *MockDatabaseService_GetSet_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetById provides a mock function with given fields: id
func (_m *MockDatabaseService) GetSetById(id int) (*models.Set, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSetById")
	}

	var r0 *models.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Set, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Set); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetSetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetById'
type MockDatabaseService_GetSetById_Call struct {
	*mock.Call
}

// GetSetById is a helper method to define mock.On call
//   - id int
func (_e *MockDatabaseService_Expecter) GetSetById(id interface{}) *MockDatabaseService_GetSetById_Call {
	return &MockDatabaseService_GetSetById_Call{Call: _e.mock.On("GetSetById", id)}
}

func (_c *MockDatabaseService_GetSetById_Call) Run(run func(id int)) *MockDatabaseService_GetSetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseService_GetSetById_Call) Return(_a0 *models.Set, _a1 error) *MockDatabaseService_GetSetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetSetById_Call) RunAndReturn(run func(int) (*models.Set, error)) *MockDatabaseService_GetSetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetSets provides a mock function with given fields: params
func (_m *MockDatabaseService) GetSets(params database.QueryParams) ([]models.Set, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetSets")
	}

	var r0 []models.Set
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) ([]models.Set, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) []models.Set); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Set)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSets'
type MockDatabaseService_GetSets_Call struct {
	*mock.Call
}

// GetSets is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetSets(params interface{}) *MockDatabaseService_GetSets_Call {
	return &MockDatabaseService_GetSets_Call{Call: _e.mock.On("GetSets", params)}
}

func (_c *MockDatabaseService_GetSets_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetSets_Call) Return(_a0 []models.Set, _a1 error) *MockDatabaseService_GetSets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetSets_Call) RunAndReturn(run func(database.QueryParams) ([]models.Set, error)) *MockDatabaseService_GetSets_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: params
func (_m *MockDatabaseService) GetUser(params *database.QueryParams) (*models.User, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*database.QueryParams) (*models.User, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*database.QueryParams) *models.User); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockDatabaseService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - params *database.QueryParams
func (_e *MockDatabaseService_Expecter) GetUser(params interface{}) *MockDatabaseService_GetUser_Call {
	return &MockDatabaseService_GetUser_Call{Call: _e.mock.On("GetUser", params)}
}

func (_c *MockDatabaseService_GetUser_Call) Run(run func(params *database.QueryParams)) *MockDatabaseService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetUser_Call) Return(_a0 *models.User, _a1 error) *MockDatabaseService_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetUser_Call) RunAndReturn(run func(*database.QueryParams) (*models.User, error)) *MockDatabaseService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: id
func (_m *MockDatabaseService) GetUserById(id int) (*models.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockDatabaseService_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id int
func (_e *MockDatabaseService_Expecter) GetUserById(id interface{}) *MockDatabaseService_GetUserById_Call {
	return &MockDatabaseService_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *MockDatabaseService_GetUserById_Call) Run(run func(id int)) *MockDatabaseService_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockDatabaseService_GetUserById_Call) Return(_a0 *models.User, _a1 error) *MockDatabaseService_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetUserById_Call) RunAndReturn(run func(int) (*models.User, error)) *MockDatabaseService_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: params
func (_m *MockDatabaseService) GetUsers(params database.QueryParams) ([]models.User, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(database.QueryParams) ([]models.User, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(database.QueryParams) []models.User); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(database.QueryParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabaseService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockDatabaseService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - params database.QueryParams
func (_e *MockDatabaseService_Expecter) GetUsers(params interface{}) *MockDatabaseService_GetUsers_Call {
	return &MockDatabaseService_GetUsers_Call{Call: _e.mock.On("GetUsers", params)}
}

func (_c *MockDatabaseService_GetUsers_Call) Run(run func(params database.QueryParams)) *MockDatabaseService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(database.QueryParams))
	})
	return _c
}

func (_c *MockDatabaseService_GetUsers_Call) Return(_a0 []models.User, _a1 error) *MockDatabaseService_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabaseService_GetUsers_Call) RunAndReturn(run func(database.QueryParams) ([]models.User, error)) *MockDatabaseService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabaseService creates a new instance of MockDatabaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseService {
	mock := &MockDatabaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
