// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	imagefile "github.com/iconifyit/go-batch-svg-to-webp/src/image-file"

	mock "github.com/stretchr/testify/mock"
)

// MockImageProcessor is an autogenerated mock type for the IImageProcessor type
type MockImageProcessor struct {
	mock.Mock
}

type MockImageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageProcessor) EXPECT() *MockImageProcessor_Expecter {
	return &MockImageProcessor_Expecter{mock: &_m.Mock}
}

// ImageFiles provides a mock function with given fields: files
func (_m *MockImageProcessor) ImageFiles(files []string) []imagefile.ImageFile {
	ret := _m.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for ImageFiles")
	}

	var r0 []imagefile.ImageFile
	if rf, ok := ret.Get(0).(func([]string) []imagefile.ImageFile); ok {
		r0 = rf(files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]imagefile.ImageFile)
		}
	}

	return r0
}

// MockImageProcessor_ImageFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageFiles'
type MockImageProcessor_ImageFiles_Call struct {
	*mock.Call
}

// ImageFiles is a helper method to define mock.On call
//   - files []string
func (_e *MockImageProcessor_Expecter) ImageFiles(files interface{}) *MockImageProcessor_ImageFiles_Call {
	return &MockImageProcessor_ImageFiles_Call{Call: _e.mock.On("ImageFiles", files)}
}

func (_c *MockImageProcessor_ImageFiles_Call) Run(run func(files []string)) *MockImageProcessor_ImageFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockImageProcessor_ImageFiles_Call) Return(_a0 []imagefile.ImageFile) *MockImageProcessor_ImageFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_ImageFiles_Call) RunAndReturn(run func([]string) []imagefile.ImageFile) *MockImageProcessor_ImageFiles_Call {
	_c.Call.Return(run)
	return _c
}

// IsLocalRun provides a mock function with no fields
func (_m *MockImageProcessor) IsLocalRun() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLocalRun")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockImageProcessor_IsLocalRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLocalRun'
type MockImageProcessor_IsLocalRun_Call struct {
	*mock.Call
}

// IsLocalRun is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) IsLocalRun() *MockImageProcessor_IsLocalRun_Call {
	return &MockImageProcessor_IsLocalRun_Call{Call: _e.mock.On("IsLocalRun")}
}

func (_c *MockImageProcessor_IsLocalRun_Call) Run(run func()) *MockImageProcessor_IsLocalRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_IsLocalRun_Call) Return(_a0 bool) *MockImageProcessor_IsLocalRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_IsLocalRun_Call) RunAndReturn(run func() bool) *MockImageProcessor_IsLocalRun_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidContributor provides a mock function with given fields: username
func (_m *MockImageProcessor) IsValidContributor(username string) bool {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for IsValidContributor")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockImageProcessor_IsValidContributor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidContributor'
type MockImageProcessor_IsValidContributor_Call struct {
	*mock.Call
}

// IsValidContributor is a helper method to define mock.On call
//   - username string
func (_e *MockImageProcessor_Expecter) IsValidContributor(username interface{}) *MockImageProcessor_IsValidContributor_Call {
	return &MockImageProcessor_IsValidContributor_Call{Call: _e.mock.On("IsValidContributor", username)}
}

func (_c *MockImageProcessor_IsValidContributor_Call) Run(run func(username string)) *MockImageProcessor_IsValidContributor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageProcessor_IsValidContributor_Call) Return(_a0 bool) *MockImageProcessor_IsValidContributor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_IsValidContributor_Call) RunAndReturn(run func(string) bool) *MockImageProcessor_IsValidContributor_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirs provides a mock function with given fields: rootdir
func (_m *MockImageProcessor) ListDirs(rootdir string) ([]string, error) {
	ret := _m.Called(rootdir)

	if len(ret) == 0 {
		panic("no return value specified for ListDirs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(rootdir)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(rootdir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rootdir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageProcessor_ListDirs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirs'
type MockImageProcessor_ListDirs_Call struct {
	*mock.Call
}

// ListDirs is a helper method to define mock.On call
//   - rootdir string
func (_e *MockImageProcessor_Expecter) ListDirs(rootdir interface{}) *MockImageProcessor_ListDirs_Call {
	return &MockImageProcessor_ListDirs_Call{Call: _e.mock.On("ListDirs", rootdir)}
}

func (_c *MockImageProcessor_ListDirs_Call) Run(run func(rootdir string)) *MockImageProcessor_ListDirs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageProcessor_ListDirs_Call) Return(_a0 []string, _a1 error) *MockImageProcessor_ListDirs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageProcessor_ListDirs_Call) RunAndReturn(run func(string) ([]string, error)) *MockImageProcessor_ListDirs_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with no fields
func (_m *MockImageProcessor) ListFiles() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageProcessor_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockImageProcessor_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) ListFiles() *MockImageProcessor_ListFiles_Call {
	return &MockImageProcessor_ListFiles_Call{Call: _e.mock.On("ListFiles")}
}

func (_c *MockImageProcessor_ListFiles_Call) Run(run func()) *MockImageProcessor_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_ListFiles_Call) Return(_a0 []string, _a1 error) *MockImageProcessor_ListFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageProcessor_ListFiles_Call) RunAndReturn(run func() ([]string, error)) *MockImageProcessor_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ListFilesForContributor provides a mock function with given fields: contributor
func (_m *MockImageProcessor) ListFilesForContributor(contributor string) ([]string, error) {
	ret := _m.Called(contributor)

	if len(ret) == 0 {
		panic("no return value specified for ListFilesForContributor")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(contributor)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(contributor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(contributor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageProcessor_ListFilesForContributor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFilesForContributor'
type MockImageProcessor_ListFilesForContributor_Call struct {
	*mock.Call
}

// ListFilesForContributor is a helper method to define mock.On call
//   - contributor string
func (_e *MockImageProcessor_Expecter) ListFilesForContributor(contributor interface{}) *MockImageProcessor_ListFilesForContributor_Call {
	return &MockImageProcessor_ListFilesForContributor_Call{Call: _e.mock.On("ListFilesForContributor", contributor)}
}

func (_c *MockImageProcessor_ListFilesForContributor_Call) Run(run func(contributor string)) *MockImageProcessor_ListFilesForContributor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockImageProcessor_ListFilesForContributor_Call) Return(_a0 []string, _a1 error) *MockImageProcessor_ListFilesForContributor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageProcessor_ListFilesForContributor_Call) RunAndReturn(run func(string) ([]string, error)) *MockImageProcessor_ListFilesForContributor_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessFiles provides a mock function with no fields
func (_m *MockImageProcessor) ProcessFiles() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProcessFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageProcessor_ProcessFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessFiles'
type MockImageProcessor_ProcessFiles_Call struct {
	*mock.Call
}

// ProcessFiles is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) ProcessFiles() *MockImageProcessor_ProcessFiles_Call {
	return &MockImageProcessor_ProcessFiles_Call{Call: _e.mock.On("ProcessFiles")}
}

func (_c *MockImageProcessor_ProcessFiles_Call) Run(run func()) *MockImageProcessor_ProcessFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_ProcessFiles_Call) Return(_a0 error) *MockImageProcessor_ProcessFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_ProcessFiles_Call) RunAndReturn(run func() error) *MockImageProcessor_ProcessFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with no fields
func (_m *MockImageProcessor) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageProcessor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockImageProcessor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) Run() *MockImageProcessor_Run_Call {
	return &MockImageProcessor_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockImageProcessor_Run_Call) Run(run func()) *MockImageProcessor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_Run_Call) Return(_a0 error) *MockImageProcessor_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_Run_Call) RunAndReturn(run func() error) *MockImageProcessor_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetupLogging provides a mock function with no fields
func (_m *MockImageProcessor) SetupLogging() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupLogging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageProcessor_SetupLogging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupLogging'
type MockImageProcessor_SetupLogging_Call struct {
	*mock.Call
}

// SetupLogging is a helper method to define mock.On call
func (_e *MockImageProcessor_Expecter) SetupLogging() *MockImageProcessor_SetupLogging_Call {
	return &MockImageProcessor_SetupLogging_Call{Call: _e.mock.On("SetupLogging")}
}

func (_c *MockImageProcessor_SetupLogging_Call) Run(run func()) *MockImageProcessor_SetupLogging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockImageProcessor_SetupLogging_Call) Return(_a0 error) *MockImageProcessor_SetupLogging_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_SetupLogging_Call) RunAndReturn(run func() error) *MockImageProcessor_SetupLogging_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldInclude provides a mock function with given fields: filePath
func (_m *MockImageProcessor) ShouldInclude(filePath *string) bool {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ShouldInclude")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*string) bool); ok {
		r0 = rf(filePath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockImageProcessor_ShouldInclude_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldInclude'
type MockImageProcessor_ShouldInclude_Call struct {
	*mock.Call
}

// ShouldInclude is a helper method to define mock.On call
//   - filePath *string
func (_e *MockImageProcessor_Expecter) ShouldInclude(filePath interface{}) *MockImageProcessor_ShouldInclude_Call {
	return &MockImageProcessor_ShouldInclude_Call{Call: _e.mock.On("ShouldInclude", filePath)}
}

func (_c *MockImageProcessor_ShouldInclude_Call) Run(run func(filePath *string)) *MockImageProcessor_ShouldInclude_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*string))
	})
	return _c
}

func (_c *MockImageProcessor_ShouldInclude_Call) Return(_a0 bool) *MockImageProcessor_ShouldInclude_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_ShouldInclude_Call) RunAndReturn(run func(*string) bool) *MockImageProcessor_ShouldInclude_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageProcessor creates a new instance of MockImageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageProcessor {
	mock := &MockImageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
