// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	fileservice "github.com/iconifyit/go-batch-svg-to-webp/src/file-service"
	imagefile "github.com/iconifyit/go-batch-svg-to-webp/src/image-file"

	mock "github.com/stretchr/testify/mock"
)

// MockS3FileService is an autogenerated mock type for the IS3FileService type
type MockS3FileService struct {
	mock.Mock
}

type MockS3FileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3FileService) EXPECT() *MockS3FileService_Expecter {
	return &MockS3FileService_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: file, dest
func (_m *MockS3FileService) Download(file *imagefile.ImageFile, dest string) (string, error) {
	ret := _m.Called(file, dest)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*imagefile.ImageFile, string) (string, error)); ok {
		return rf(file, dest)
	}
	if rf, ok := ret.Get(0).(func(*imagefile.ImageFile, string) string); ok {
		r0 = rf(file, dest)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*imagefile.ImageFile, string) error); ok {
		r1 = rf(file, dest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3FileService_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockS3FileService_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - file *imagefile.ImageFile
//   - dest string
func (_e *MockS3FileService_Expecter) Download(file interface{}, dest interface{}) *MockS3FileService_Download_Call {
	return &MockS3FileService_Download_Call{Call: _e.mock.On("Download", file, dest)}
}

func (_c *MockS3FileService_Download_Call) Run(run func(file *imagefile.ImageFile, dest string)) *MockS3FileService_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*imagefile.ImageFile), args[1].(string))
	})
	return _c
}

func (_c *MockS3FileService_Download_Call) Return(_a0 string, _a1 error) *MockS3FileService_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3FileService_Download_Call) RunAndReturn(run func(*imagefile.ImageFile, string) (string, error)) *MockS3FileService_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: objectKey
func (_m *MockS3FileService) Exists(objectKey string) (bool, error) {
	ret := _m.Called(objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(objectKey)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(objectKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(objectKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3FileService_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockS3FileService_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - objectKey string
func (_e *MockS3FileService_Expecter) Exists(objectKey interface{}) *MockS3FileService_Exists_Call {
	return &MockS3FileService_Exists_Call{Call: _e.mock.On("Exists", objectKey)}
}

func (_c *MockS3FileService_Exists_Call) Run(run func(objectKey string)) *MockS3FileService_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockS3FileService_Exists_Call) Return(_a0 bool, _a1 error) *MockS3FileService_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3FileService_Exists_Call) RunAndReturn(run func(string) (bool, error)) *MockS3FileService_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function with given fields: input, filter
func (_m *MockS3FileService) ListFiles(input fileservice.ListFilesInput, filter func(*string) bool) ([]string, error) {
	ret := _m.Called(input, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(fileservice.ListFilesInput, func(*string) bool) ([]string, error)); ok {
		return rf(input, filter)
	}
	if rf, ok := ret.Get(0).(func(fileservice.ListFilesInput, func(*string) bool) []string); ok {
		r0 = rf(input, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(fileservice.ListFilesInput, func(*string) bool) error); ok {
		r1 = rf(input, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3FileService_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockS3FileService_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - input fileservice.ListFilesInput
//   - filter func(*string) bool
func (_e *MockS3FileService_Expecter) ListFiles(input interface{}, filter interface{}) *MockS3FileService_ListFiles_Call {
	return &MockS3FileService_ListFiles_Call{Call: _e.mock.On("ListFiles", input, filter)}
}

func (_c *MockS3FileService_ListFiles_Call) Run(run func(input fileservice.ListFilesInput, filter func(*string) bool)) *MockS3FileService_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fileservice.ListFilesInput), args[1].(func(*string) bool))
	})
	return _c
}

func (_c *MockS3FileService_ListFiles_Call) Return(_a0 []string, _a1 error) *MockS3FileService_ListFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3FileService_ListFiles_Call) RunAndReturn(run func(fileservice.ListFilesInput, func(*string) bool) ([]string, error)) *MockS3FileService_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ToImageFiles provides a mock function with given fields: files
func (_m *MockS3FileService) ToImageFiles(files []string) ([]*imagefile.ImageFile, error) {
	ret := _m.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for ToImageFiles")
	}

	var r0 []*imagefile.ImageFile
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*imagefile.ImageFile, error)); ok {
		return rf(files)
	}
	if rf, ok := ret.Get(0).(func([]string) []*imagefile.ImageFile); ok {
		r0 = rf(files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*imagefile.ImageFile)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(files)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3FileService_ToImageFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToImageFiles'
type MockS3FileService_ToImageFiles_Call struct {
	*mock.Call
}

// ToImageFiles is a helper method to define mock.On call
//   - files []string
func (_e *MockS3FileService_Expecter) ToImageFiles(files interface{}) *MockS3FileService_ToImageFiles_Call {
	return &MockS3FileService_ToImageFiles_Call{Call: _e.mock.On("ToImageFiles", files)}
}

func (_c *MockS3FileService_ToImageFiles_Call) Run(run func(files []string)) *MockS3FileService_ToImageFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockS3FileService_ToImageFiles_Call) Return(_a0 []*imagefile.ImageFile, _a1 error) *MockS3FileService_ToImageFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3FileService_ToImageFiles_Call) RunAndReturn(run func([]string) ([]*imagefile.ImageFile, error)) *MockS3FileService_ToImageFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function with given fields: input
func (_m *MockS3FileService) Transfer(input fileservice.TransferInput) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(fileservice.TransferInput) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3FileService_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type MockS3FileService_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - input fileservice.TransferInput
func (_e *MockS3FileService_Expecter) Transfer(input interface{}) *MockS3FileService_Transfer_Call {
	return &MockS3FileService_Transfer_Call{Call: _e.mock.On("Transfer", input)}
}

func (_c *MockS3FileService_Transfer_Call) Run(run func(input fileservice.TransferInput)) *MockS3FileService_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(fileservice.TransferInput))
	})
	return _c
}

func (_c *MockS3FileService_Transfer_Call) Return(_a0 error) *MockS3FileService_Transfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3FileService_Transfer_Call) RunAndReturn(run func(fileservice.TransferInput) error) *MockS3FileService_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: localPath, objectKey
func (_m *MockS3FileService) Upload(localPath string, objectKey string) error {
	ret := _m.Called(localPath, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(localPath, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3FileService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3FileService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - localPath string
//   - objectKey string
func (_e *MockS3FileService_Expecter) Upload(localPath interface{}, objectKey interface{}) *MockS3FileService_Upload_Call {
	return &MockS3FileService_Upload_Call{Call: _e.mock.On("Upload", localPath, objectKey)}
}

func (_c *MockS3FileService_Upload_Call) Run(run func(localPath string, objectKey string)) *MockS3FileService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockS3FileService_Upload_Call) Return(_a0 error) *MockS3FileService_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3FileService_Upload_Call) RunAndReturn(run func(string, string) error) *MockS3FileService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockS3FileService creates a new instance of MockS3FileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3FileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3FileService {
	mock := &MockS3FileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
